name: Array Test
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, closed]

jobs:
  second:
    name: second test
    runs-on: ubuntu-22.04
    if: >
      (
        github.event.action == 'closed' 
          && (
            contains(github.event.pull_request.labels.*.name, '[feature] backend') 
            || contains(github.event.pull_request.labels.*.name, '[feature] backend-ha')
          )
      )
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0 commit hash
      - run: echo "${{ github.event.pull_request.labels.*.name }}"
      - name: delete front feature env
        run: |          
          labels=('[feature] backend' '[feature] backend-ha')
          repos=(park-direct-front-client park-direct-front-customer)
          workflow_ids=(deploy_feature_environments.yaml  deploy_feature_environments.yml)
          ACTION="remove"

          for ((i = 0; i <= 1; i++)); do
            label=${labels[$i]}
            REPO=${repos[$i]}
            WORKFLOWS_ID=${workflow_ids[$i]}
            if [[ "${{ github.event.pull_request.labels.*.name }}" == *"$label"* ]]; then
              echo "passed $i"
            fi
          done

 