name: Owner

on:
  workflow_dispatch:


jobs:
  final:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0 commit hash
      - name: collect status
        run: |
          owner="${{ github.actor }}"
          echo "OWNER=$owner" >> $GITHUB_ENV
          echo "${{ env.OWNER }}"
