name: Deployment feature environments

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, closed]

jobs:
  first:
    name: first test
    runs-on: ubuntu-22.04
    if: >
      (
        (github.event.label.name == '[feature] backend' || github.event.label.name == '[feature] backend-ha' )
        && github.event.action == 'unlabeled'
      )

    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0 commit hash
      - run: echo "unlabeled"

  second:
    name: second test
    runs-on: ubuntu-22.04
    if: >
      (
        github.event.action == 'closed' 
          && (
            contains(github.event.pull_request.labels.*.name, '[feature] backend') 
            || contains(github.event.pull_request.labels.*.name, '[feature] backend-ha')
          )
      )
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0 commit hash
      - run: echo "closed"

  third:
    name: third test
    runs-on: ubuntu-22.04
    if: >
      (
        github.event.action == 'closed' 
          && (
            github.event.pull_request.labels.*.name == *'[feature] backend'*
            ||github.event.pull_request.labels.*.name == *'[feature] backend-ha'*)
          )
      )
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0 commit hash
      - run: echo "merged"
